plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - bin/bundle
    - config/initializers/devise.rb
    - db/schema.rb
    - db/queue_schema.rb
    - db/cache_schema.rb
    - db/cable_schema.rb

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - spec/**/*
