require:
  - rubocop-performance
  - rubocop-rails
#   - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - db/queue_schema.rb
    - db/cache_schema.rb
    - db/cable_schema.rb

Style/Documentation:
  Enabled: false
